### ISSUE TITLE
deploy to maven central

### ISSUE THREAD

**Issue by maxthomas** [NextCenturyCorporation/AIDA-Interchange-Format#176]
hi, it'd be really useful to get this deployed to an OSS repo so that it's not necessary to clone the repo and `mvn install` it.

are there any procedural or legal concerns about doing this? if not, is this something we could take on?

**Comment by craigwarsaw** [comment]
Max, it's never been done simply because before this, nobody requested it.  I'm sure it would make developers' lives easier and we support this. This repo is already public and has an MIT license. We've received approval from DARPA to make it public. There should be no legal concerns for doing this.

As far as procedural concerns go, up to this point, we haven't been very clear about release numbering, and we would need a documented procedure for posting updates.  We are close to making the final updates required by the AIDA evaluation plan v1.1, so that might be a good time to consider doing this.  If this is something your team would like to help with, let's discuss.

**Comment by nextcen-dgemoets** [comment]
Max, this is a task we're investigating now for the newly-released [AIF v1.0.2](https://github.com/NextCenturyCorporation/AIDA-Interchange-Format/releases).  We'll let you know when we have something available in OSS Repository Hosting.

**Comment by ecurley-nextcentury** [comment]
https://search.maven.org/artifact/com.github.nextcenturycorporation/aida-interchange/1.2.1/jar

Closing
