### ISSUE TITLE
Add optional uri_ref to mark_as_possible_cluster_member()

### ISSUE THREAD

**Issue by rogerbock** [NextCenturyCorporation/AIDA-Interchange-Format#227]
This is extending what was done in #88 to this new function.

For BBN, we find it useful to diff our output when running regression tests, so avoiding blank nodes is important as they are printed in a non-deterministic order.

**Comment by craigwarsaw** [comment]
This will need a corresponding change to the Java version.  We consider this an enhancement request and have prioritized it as such.  Please let us know if making this change to 1.1.0-SNAPSHOT (i.e., master branch) rather than updating 1.0.x (i.e., releases/v1.0 branch) is sufficient for your needs.

**Comment by rogerbock** [comment]
I have a modified local copy, so there is no rush on my end.  I just want to make sure it makes it into the eventual next release.  Thanks!

**Comment by nextcen-dgemoets** [comment]
FYI, this change has been made to our master branch.  It is currently slated to go into the next version of AIF (v1.0.4), though we don't have a release date for that at the moment.

**Comment by nextcen-dgemoets** [comment]
AIF v1.0.4 has been released and contains this fix.  Closing this issue.
